version: 2

project_name: chainctl

before:
  hooks:
    - go mod tidy

builds:
  - id: chainctl
    main: .
    binary: chainctl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X chainctl/internal/version.Value={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: chainctl
    ids:
      - chainctl
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: github

release:
  github:
    owner: AleMoz97
    name: chainctl
